### ISSUE TITLE
Thanks for obsidian-csv fork -- and question

### ISSUE THREAD

**Issue by ReessKennedy** [Sayama3/LearnOpenGL#1]
Hey @Sayama3 -- I was trying to find your email but couldn't find it to email you there so trying here. Just wanted to thank you so much for the Obsidian-CSV plugin. I'm actually surprised more people aren't using it. The one it's forked from looks like it's no longer maintained but yours actually works! Much appreciated! -Reess

**Comment by ReessKennedy** [comment]
My email/info is in my profile. Would be great to connect. Merci!

**Comment by Sayama3** [comment]
Hello @ReessKennedy ,

I'm pretty surprised you found the Obsidian-CSV plugins, and even more that it still works. It was about a year ago that I've worked on that.

And I think the reason people don't use it is that it's not referenced on obsidian (because I've just forked it to try and make it kinda works. There are still bugs mentioned in the README if I recall correctly). If I wanted to make my own, I would fork the official repo and follow all the process. But as I don't use Obsidian as much as I thought, I didn't make the effort to implement a whole CSV plugins and integrate it seamlessly with all the features Obsidian has.

Anyway, still glad to hear people appreciate the little work.

Have a nice day,
Sayama

(PS: I couldn't find an email either...)
